# Generated by Django 3.2.7 on 2026-03-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(help_text='Role headline shown under the photo', max_length=300)),
                ('linkedin_url', models.URLField(blank=True)),
                ('linkedin_label', models.CharField(blank=True, default='linkedin.com/in/gwibmer', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('linkedin_url', models.URLField(blank=True)),
                ('linkedin_label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=300)),
                ('start_year', models.CharField(max_length=20)),
                ('end_year', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('responsibilities', models.TextField(help_text='One bullet point per line')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gerardo Wibmer', max_length=100)),
                ('typed_items', models.CharField(default='Full-Stack Developer, AI/ML Engineer, Software Engineer, Freelancer', help_text='Comma-separated list of items for the typing animation', max_length=500)),
            ],
            options={
                'verbose_name': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('filter-django', 'Django'), ('filter-ml', 'Machine Learning')], max_length=20)),
                ('image_path', models.CharField(help_text='Static file path, e.g. img/portfolio/preview/SAL_1_preview.png', max_length=300)),
                ('detail_url', models.CharField(help_text='URL for the detail page, e.g. /project', max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Projects Section',
            },
        ),
        migrations.CreateModel(
            name='ResumeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_description', models.TextField(help_text='Intro paragraph shown at the top of the Resume section')),
                ('name', models.CharField(max_length=100)),
                ('summary_text', models.TextField(help_text='Short italic bio under your name in the summary card')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Resume Summary',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('column', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SkillsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Skills Section',
            },
        ),
    ]
