# Generated by Django 3.2.7 on 2026-03-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutsection_contactsection_education_experience_herosection_project_projectssection_resumesummary_s'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='column',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Frameworks & Libraries', 'Frameworks & Libraries'), ('Tools & Platforms', 'Tools & Platforms'), ('AI / ML', 'AI / ML')], default='Languages', max_length=50),
        ),
    ]
