# Generated by Django 3.2.7 on 2026-03-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20260315_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='details',
            field=models.CharField(blank=True, help_text='e.g. GPA 3.83', max_length=100),
        ),
        migrations.AddField(
            model_name='resumesummary',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resumesummary',
            name='subtitle',
            field=models.CharField(blank=True, help_text='e.g. AI & Full-Stack Engineer · Tampa, FL', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumesummary',
            name='section_description',
            field=models.TextField(blank=True, help_text='Intro paragraph shown at the top of the Resume section'),
        ),
        migrations.AlterField(
            model_name='resumesummary',
            name='summary_text',
            field=models.TextField(help_text='Bio paragraph shown below the header'),
        ),
    ]
