# Generated by Django 3.2.7 on 2026-03-15 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20260315_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='detail_url',
        ),
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True, help_text='HTML content for the detail body'),
        ),
        migrations.AddField(
            model_name='project',
            name='info_category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='info_client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='info_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='info_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='info_technologies',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='', help_text='URL identifier, e.g. sal-sentiment-analysis', max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(help_text='Static file path, e.g. img/portfolio/slider/SAL_1_slider.png', max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
